config/routes.rb
Contentify::Engine.routes.draw do
  resources :categories, except: [:show]
  resources :users,      except: [:show]
  resources :contents
  resources :materials,  except: [:show]
  resources :user_sessions, only: [:create]
  get    'login',  to: 'user_sessions#new',     as: :login
  delete 'logout', to: 'user_sessions#destroy', as: :logout
end

app/models/contentify/categories_content.rb
module Contentify
  class CategoriesContent < ActiveRecord::Base
    belongs_to :category
    belongs_to :content
  end
end

app/models/contentify/category.rb
module Contentify
  class Category < ActiveRecord::Base
    extend ActiveHash::Associations::ActiveRecordExtensions

    attr_accessor :display_name

    has_closure_tree order: :priority, dependent: :nullify

    has_many :categories_contents
    has_many :contents, through: :categories_contents

    belongs_to_active_hash :public_status, class_name: 'Contentify::PublicStatus'

    accepts_nested_attributes_for :categories_contents, allow_destroy: true

    mount_uploader :image, FileUploader

    validates :priority,
              presence: true
    validates :name,
              presence: true,
              length: { maximum: 50 }
    validates :slug,
              presence: true,
              length: { maximum: 50 }
    validates :direct_url
              length: { maximum: 500 }



    def self.display_tree
      self.hash_tree_to_array(self.hash_tree)
    end

    private
    def self.hash_tree_to_array(hash, depth = "|--")
      tree = []
      hash.each do |k, v|
        k.display_name = "#{depth}#{k.name}"
        tree << k
        if v.present?
          case v
          when ActiveSupport::OrderedHash
            tree += self.hash_tree_to_array(v, depth.gsub('|--', '|  ') << "|--")
          end
        end
      end
      tree
    end
  end
end

app/models/contentify/concerns/date_time_integratable.rb
module Contentify
  module Concerns
    module DateTimeIntegratable
      extend ActiveSupport::Concern

      included do
        after_initialize :initialize_integrate_datetime
        before_validation :integrate_datetime

        def initialize_integrate_datetime
          self.class.datetime_integrate_targets.each do |attribute|
            next unless self.respond_to?("#{attribute}")
            original_date = self.send("#{attribute}")
            next if original_date.nil?
            unless self.send("#{attribute}_date").present?
              self.send("#{attribute}_date=", original_date.strftime("%Y-%m-%d"))
            end
            unless self.send("#{attribute}_hour").present?
              self.send("#{attribute}_hour=", original_date.strftime("%H"))
            end
            unless self.send("#{attribute}_minute").present?
              self.send("#{attribute}_minute=", original_date.strftime("%M"))
            end
          end
        end

        def integrate_datetime
          self.class.datetime_integrate_targets.each do |attribute|
            date = self.send("#{attribute}_date")
            hour = self.send("#{attribute}_hour")
            minute = self.send("#{attribute}_minute")
            if date.present? && hour.present? && minute.present?
              self.send("#{attribute}=", Time.zone.parse("#{date} #{hour}:#{minute}:00"))
            else
              self.send("#{attribute}=", nil)
            end
          end
        rescue
          nil
        end
      end

      module ClassMethods
        attr_accessor :datetime_integrate_targets

        def integrate_datetime_fields(*attributes)
          self.datetime_integrate_targets = attributes
          attributes.each do |attribute|
            self.send(:attr_accessor, "#{attribute}_date")
            self.send(:attr_accessor, "#{attribute}_hour")
            self.send(:attr_accessor, "#{attribute}_minute")
          end
        end
      end
    end
  end
end

app/models/contentify/content.rb
module Contentify
  class Content < ActiveRecord::Base
    extend ActiveHash::Associations::ActiveRecordExtensions

    include Contentify::Concerns::DateTimeIntegratable

    has_many :categories_contents
    has_many :categories, through: :categories_contents

    belongs_to_active_hash :public_status, class_name: 'Contentify::PublicStatus'

    accepts_nested_attributes_for :categories_contents, allow_destroy: true

    integrate_datetime_fields :released_at, :closed_at

    mount_uploader :summary_image, FileUploader

    # validates
    validates :title,
              presence: true,
              length: { maximum: 255 }
    validates :summary, length: { maximum: 500 }
    validates :summary, length: { maximum: 100 }
    validates :author_name, length: { maximum: 50 }
    validates :body, presence: true
    validates :released_at, presence: true
  end
end

app/models/contentify/material.rb
module Contentify
  class Material < ActiveRecord::Base
    mount_uploader :source, FileUploader

    validates :source,
              presence: true

    validates :title,
              presence: true
  end
end

app/models/contentify/public_status.rb
module Contentify
  class PublicStatus < ActiveYaml::Base
    set_root_path Contentify::Engine.root + "config/master"
    set_filename "public_status"

    include ActiveHash::Enum
    include ActiveHash::Associations

    enum_accessor :type

    has_many :contents
    has_many :categories

    class << self
      def display_assoc
        all.map do |m| [m.name, m.id] end
      end
    end
  end
end

app/models/contentify/search/base.rb
module Contentify
  class Search::Base
    include ActiveModel::Model
    include ActiveModel::Validations::Callbacks
  end
end

app/models/contentify/search/content.rb
module Contentify
  class Search::Content < Search::Base

    attr_accessor :title, :category_id

    def initialize(attributes = {})
      super attributes if attributes.present?
    end

    def matches
      results = Contentify::Content
        .joins(:category)
        .includes(:category)
        .references(:category)
        .where { category.id == my { category_id } }
      results = results.where { title.like my { "%#{title}%" } } if title.present?
      results = results.where { released_at >= my { released_at_from.to_time.try(:beginning_of_day) } } if released_at_from.present?
      results = results.where { released_at <= my { released_at_to.to_time.try(:end_of_day) } } if released_at_to.present?
      results = results.where(top: true) if top.present? && top != "0"
      results = results.where(business_top: true) if business_top.present? && business_top != "0"
      results
    end
  end
end

app/models/contentify/user.rb
module Contentify
  class User < ActiveRecord::Base
    authenticates_with_sorcery!

    attr_accessor :password_confirmation

    mount_uploader :image, FileUploader

    validates :password, length: { minimum: 12 }
    validates :password, confirmation: true
    validates :password_confirmation, presence: true
    validates :email, uniqueness: true
  end
end

app/controllers/contentify/application_controller.rb
module Contentify
  class ApplicationController < ActionController::Base
    before_action :set_as_private!
    before_action :require_login

    private
    def set_as_private!
      response.headers['Cache-Control'] = 'no-cache, no-store'
    end

    def not_authenticated
      redirect_to login_path, alert: "ログインしてください。"
    end
  end
end

app/controllers/contentify/categories_controller.rb
require_dependency "contentify/application_controller"

module Contentify
  class CategoriesController < ApplicationController
    include Concerns::BasicController::New
    include Concerns::BasicController::Create
    include Concerns::BasicController::Edit
    include Concerns::BasicController::Update
    include Concerns::BasicController::Destroy

    registrable_params_as    :registrable_params
    success_redirect_path_as :categories_path
    fault_redirect_path_as   :categories_path
    notice_attribute_as      :name

    def index
      @categories = Contentify::Category.display_tree
    end

    def registrable_params
      params.require(:category).permit(
        :parent_id,
        :priority,
        :public_status_id,
        :name,
        :slug,
        :direct_url,
        :image,
        :is_visible
      )
    end
  end
end

app/controllers/contentify/concerns/basic_controller.rb
module Contentify
  module Concerns
    # give the basic controll method
    module BasicController

      module Base
        extend ActiveSupport::Concern

        included do
          def models_name
            self.send(:params)[:controller].split("/").last
          end

          def model_name
            self.send(:params)[:controller].camelize.singularize
          end
        end

        module ClassMethods
          attr_accessor :registrable_params,
                        :success_redirect_path,
                        :fault_redirect_path,
                        :notice_attribute

          def registrable_params_as(method_name)
            self.registrable_params = method_name
          end

          def success_redirect_path_as(path)
            self.success_redirect_path = path
          end

          def fault_redirect_path_as(path)
            self.fault_redirect_path = path
          end

          def notice_attribute_as(attribute_name)
            self.notice_attribute = attribute_name
          end
        end
      end

      module Index
        extend ActiveSupport::Concern

        include BasicController::Base

        included do
          def index
            self.instance_variable_set(
              "@#{models_name.downcase}",
              model_name.constantize.all
            )
          end
        end
      end

      module New
        extend ActiveSupport::Concern

        include BasicController::Base

        included do
          def new
            self.instance_variable_set(
              "@#{models_name.singularize}", model_name.constantize.new)
          end
        end
      end

      module Create
        extend ActiveSupport::Concern

        include BasicController::Base

        included do
          def create
            model = model_name.constantize.new(
              self.send(self.class.registrable_params))
            if model.save
              redirect_to(
                self.send(self.class.success_redirect_path),
                # TODO use given message.
                notice: model.send(self.class.notice_attribute) << "を作成しました。")
            else
              self.instance_variable_set(
                "@#{models_name.singularize}", model_name.constantize.new)
              render :new
            end
          end
        end
      end

      module Edit
        extend ActiveSupport::Concern

        include BasicController::Base

        included do
          def edit
            model = model_name.constantize.find(params[:id])
            self.instance_variable_set("@#{models_name.singularize}", model)
          end
        end
      end

      module Update
        extend ActiveSupport::Concern

        include BasicController::Base

        included do
          def update
            model = model_name.constantize.find(params[:id])
            model.assign_attributes(self.send(self.class.registrable_params))
            if model.save
              redirect_to(
                self.send(self.class.success_redirect_path),
                notice: model.send(self.class.notice_attribute) << "を更新しました。")
            else
              self.instance_variable_set("@#{models_name.singularize}", model)
              render :edit
            end
          end
        end
      end

      module Destroy
        extend ActiveSupport::Concern

        include BasicController::Base

        included do
          def destroy
            model = model_name.constantize.find(params[:id])
            if model.destroy
              redirect_to(
                self.send(self.class.success_redirect_path),
                notice: model.send(self.class.notice_attribute) << "を削除しました。")
            else
              redirect_to(
                self.send(self.class.success_redirect_path),
                notice: model.send(self.class.notice_attribute) << "の削除に失敗しました。")
            end
          end
        end
      end

    end
  end
end

app/controllers/contentify/contents_controller.rb
require_dependency "contentify/application_controller"

module Contentify
  class ContentsController < ApplicationController
    include Contentify::Concerns::BasicController::New
    include Contentify::Concerns::BasicController::Create
    include Contentify::Concerns::BasicController::Edit
    include Contentify::Concerns::BasicController::Update
    include Contentify::Concerns::BasicController::Destroy

    before_action :setup_editable_content!, only: [:edit, :update, :destroy]

    registrable_params_as    :registrable_params
    success_redirect_path_as :contents_path
    fault_redirect_path_as   :contents_path
    notice_attribute_as      :title

    def index
      @contents = Content.all.try(:page, params[:page])
    end

    ## use preview
    def show
    end

    private
    def registrable_params
      params.require(:content).permit(
        :public_status_id,
        :priority,
        :title,
        :summary,
        :summary_image,
        :summary_image_caption,
        :body,
        :author_name,
        :is_display_author,
        :released_at_date,
        :released_at_hour,
        :released_at_minute,
        :closed_at_date,
        :closed_at_hour,
        :closed_at_minute,
        category_ids: []
      )
    end

    def setup_editable_content!
      @content = Content.find(params[:id])
    end
  end
end

app/controllers/contentify/materials_controller.rb
require_dependency "contentify/application_controller"

module Contentify
  class MaterialsController < ApplicationController
    include Contentify::Concerns::BasicController::Index
    include Contentify::Concerns::BasicController::New
    include Contentify::Concerns::BasicController::Create
    include Contentify::Concerns::BasicController::Edit
    include Contentify::Concerns::BasicController::Update
    include Contentify::Concerns::BasicController::Destroy

    before_action :setup_editable_material!, only: [:edit, :update, :destroy]

    registrable_params_as    :registrable_params
    success_redirect_path_as :contents_path
    fault_redirect_path_as   :contents_path
    notice_attribute_as      :title

    private
    def registrable_params
      params.require(:material).permit(:title, :source)
    end

    def setup_editable_material!
      @content = Material.find(params[:id])
    end
  end
end

app/controllers/contentify/user_sessions_controller.rb
require_dependency "contentify/application_controller"

module Contentify
  class UserSessionsController < ApplicationController
    layout false

    skip_before_action :require_login

    def new
      @user = User.new
    end

    def create
      if @user = login(params[:email], params[:password])
        redirect_back_or_to(categories_path, notice: I18n.t('login.success'))
      else
        flash.now[:alert] = I18n.t('login.failed')
        render :new
      end
    end

    def destroy
      logout
      redirect_to(login_path, notice: I18n.t('logout.success'))
    end
  end
end

app/controllers/contentify/users_controller.rb
require_dependency "contentify/application_controller"

module Contentify
  class UsersController < ApplicationController
    include Concerns::BasicController::New
    include Concerns::BasicController::Create
    include Concerns::BasicController::Edit
    include Concerns::BasicController::Update
    include Concerns::BasicController::Destroy

    registrable_params_as    :registrable_params
    success_redirect_path_as :users_path
    fault_redirect_path_as   :users_path
    notice_attribute_as      :name

    def index
      @users = User.try(:page, params[:page])
    end

    def registrable_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/helpers/contentify/application_helper.rb
module Contentify
  module ApplicationHelper
    def lf2br(text)
      html_escape(text).gsub(/\r\n|\r|\n/, '<br />').html_safe
    end

    def space2br(text)
      html_escape(text).gsub(' ', '&nbsp;').html_safe
    end

    def display_error(obj, attribute)
      if has_error?(obj, attribute)
        content_tag(:div, obj.errors.full_messages_for(attribute.to_sym).first, { style: 'color: #F44336;' })
      end
    end

    def has_error?(obj, attribute)
      obj.errors.full_messages_for(attribute.to_sym).present?
    end

    def materialized_form_field(f, field_type, field_name, options = { class: '', choices: [] })
      if f.object.present? && has_error?(f.object, field_name)
        if options[:class].present?
          options[:class] << ' invalid'
        else
          options[:class] = 'invalid'
        end
      elsif f.object.present? && f.object.method(field_name).call().present?
        if options[:class].present?
          options[:class] << ' valid'
        else
          options[:class] = 'valid'
        end
      end
      if field_type == :select
        choices = options.delete(:choices)
        f.method(field_type).call(field_name, choices, { include_blank: true }, options)
      else
        f.method(field_type).call(field_name, options)
      end
    end
  end
end

app/helpers/contentify/categories_helper.rb
module Contentify
  module CategoriesHelper
  end
end

app/views/contentify/contents/_registration.html.erb
<ul class="collapsible collapsible-accordion" data-collapsible="accordion">
  <li>
    <div class="collapsible-header"><i class="material-icons">local_offer</i>カテゴリ</div>
    <div class="collapsible-body" style="display: none;">
      <ul class="collection">
        <%= f.collection_check_boxes(:category_ids, Contentify::Category.display_tree, :id, :display_name) do |b| %>
          <li class="collection-item">
            <%= b.check_box %><%= b.label %>
          </li>
        <% end %>
      </ul>
    </div>
  </li>
</ul>

<div class="row">
  <div class="input-field col s12">
    <i class="material-icons prefix tooltipped" data-position="left" data-delay="50" data-tooltip="必須">info</i>
    <%= materialized_form_field(f, :text_field, :title, { class: 'validate' }) %>
    <%= f.label :title %>
    <%= display_error(f.object, :title) %>
  </div>
</div>

<div class="row">
  <div class="input-field col s12">
    <%= materialized_form_field(f, :text_area, :summary, { class: "materialize-textarea", maxlength: 500 }) %>
    <%= f.label :summary %>
    <%= display_error(f.object, :summary) %>
  </div>
</div>

<div class="row">
  <div class="file-field input-field col s12 m6 l6">
    <div class="btn">
      <span>ファイル</span>
      <%= materialized_form_field(f, :file_field, :summary_image) %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" value="<%= f.object.summary_image.try(:file).try(:filename) || '' %>">
    </div>
    <%= f.label :summary_image, '', class: 'active' %>
    <%= display_error(f.object, :summary_image) %>
  </div>
  <div class="input-field col s12 m6 l6">
    <%= materialized_form_field(f, :text_field, :summary_image_caption) %>
    <%= f.label :summary_image_caption %>
    <%= display_error(f.object, :summary_image_caption) %>
  </div>
</div>

<!-- 表示順 -->
<div class="row">
  <div class="input-field col s12">
    <%= materialized_form_field(f, :number_field, :priority, { class: "validate", min: 1 }) %>
    <%= f.label :priority %>
    <%= display_error(f.object, :priority) %>
  </div>
</div>

<div class="row mgn-bottom-0">
  <div class="col s12 m6 l6">
    <div class="input-field col s12 m6 l6">
      <i class="material-icons prefix tooltipped" data-position="left" data-delay="50" data-tooltip="必須">info</i>
      <%= materialized_form_field(f, :text_field, :released_at_date, { class: "datepicker" }) %>
      <%= f.label :released_at_date %>
    </div>
    <div class="input-field col s6 m3 l3">
      <%= materialized_form_field(f, :select, :released_at_hour, { class: "browser-default", choices: ("00".."23").to_a }) %>
      <%= f.label :released_at_hour, class: 'active' %>
    </div>
    <div class="input-field col s6 m3 l3">
      <%= materialized_form_field(f, :select, :released_at_minute, { class: "browser-default", choices: ("00".."59").to_a }) %>
      <%= f.label :released_at_minute, class: 'active' %>
    </div>
  </div>
  <div class="col s12 m6 l6">
    <div class="input-field col s12 m6 l6">
      <%= materialized_form_field(f, :text_field, :closed_at_date, { class: "datepicker" }) %>
      <%= f.label :closed_at_date %>
    </div>
    <div class="input-field col s6 m3 l3">
      <%= materialized_form_field(f, :select, :closed_at_hour, { class: "browser-default", choices: ("00".."23").to_a }) %>
      <%= f.label :closed_at_hour, class: 'active' %>
    </div>
    <div class="input-field col s6 m3 l3">
      <%= materialized_form_field(f, :select, :closed_at_minute, { class: "browser-default", choices: ("00".."59").to_a }) %>
      <%= f.label :closed_at_minute, class: 'active' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s12 m12 l12">
    <%= materialized_form_field(f, :date_field, :released_at, { class: '', disabled: true, style: 'height: 0;' }) %>
    <%= display_error(f.object, :released_at) %>
  </div>
</div>

<div class="row">
  <div class="input-field col s12">
    <i class="material-icons prefix tooltipped" data-position="left" data-delay="50" data-tooltip="必須">info</i>
    <%= materialized_form_field(f, :text_area, :body, { class: "materialize-textarea" }) %>
    <%= f.label :body %>
    <%= display_error(f.object, :body) %>
  </div>
</div>

<!-- author -->
<div class="row">
  <div class="input-field col s12 m6 l6">
    <%= materialized_form_field(f, :check_box, :is_display_author) %>
    <%= f.label :is_display_author %>
    <%= display_error(f.object, :is_display_author) %>
  </div>
  <div class="input-field col s12 m6 l6">
    <%= materialized_form_field(f, :text_field, :author_name, { class: 'validate' }) %>
    <%= f.label :author_name %>
    <%= display_error(f.object, :author_name) %>
  </div>
</div>

<!-- public status -->
<div class="row">
  <div class="input-field col s6 offset-s3 center-align">
    <%- Contentify::PublicStatus.all.each do |status|-%>
    <%= f.radio_button :public_status_id, status.id, checked: f.object.public_status == status, class: 'with-gap' %>
    <%= f.label :public_status_id, status.name, value: status.id %>
    <%- end -%>
  </div>
</div>

app/views/contentify/contents/edit.html.erb
<%- content_for :head do-%>
<title>管理画面&nbsp;|&nbsp;記事&nbsp;|&nbsp;編集</title>
<%- end -%>
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <div class="card">
      <%= form_for(@content, url: content_path, method: :patch) do |f| %>
      <div class="card-content">
        <span class="card-title black-text">記事&nbsp;編集</span>
        <%= render 'registration', f: f %>
      </div>
      <div class="card-action center-align">
        <%= f.button '更新する', class: 'waves-effect waves-light btn white-text wine-red', data: { confirm: '更新してもよろしいですか?' } %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contentify/contents/index.html.erb
<%- content_for :head do-%>
<title>管理画面&nbsp;|&nbsp;記事&nbsp;|&nbsp;一覧</title>
<%- end -%>

<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <div class="card">
      <div class="card-content">
        <span class="card-title black-text">記事&nbsp;一覧</span>

        <div class="center-align">
          <%= paginate @contents %>
        </div>
        <table class="bordered responsive-table">
          <thead>
            <tr>
              <th data-field="title">タイトル</th>
              <th data-field="summary_image" class="center-align">概要画像</th>
              <th data-field="public_status_id" class="center-align">公開状態</th>
              <th data-field="released_at">公開日時</th>
              <th data-field="ctrl" class="center-align">操作</th>
            </tr>
          </thead>
          <tbody>
            <%- @contents.each do |content| -%>
            <tr>
              <td><%= content.title %></td>
              <td class="center-align">
                <%- if content.summary_image.present? -%>
                <img src="<%= content.summary_image %>"
                     height="100px"
                     class="img-responsive tooltipped"
                     data-position="top"
                     data-delay="250"
                     data-tooltip="<%= content.summary_image %>">
                <%- end -%>
              </td>
              <td class="center-align<%= content.public_status.bg_color %>">
                <%= content.public_status.name %>
              </td>
              <td><%= content.released_at.to_s(:display) %></td>
              <td class="center-align">
                <%= link_to '編集', edit_content_path(content), class: 'waves-effect waves-light chip white-text wine-red mgn-top-5' %>
                <%= link_to '削除', content_path(content), method: :delete, class: 'waves-effect waves-light chip black-text mgn-top-5', data: {confirm: '本当に削除しますか？'} %>
              </td>
            </tr>
            <%- end -%>
          </tbody>
        </table>
        <div class="center-align">
          <%= paginate @contents %>
        </div>
      </div>
      <div class="card-action right-align">
        <%= link_to '新規作成', new_content_path, class: 'waves-effect waves-light btn white-text wine-red' %>
      </div>
    </div>
  </div>
</div>

app/views/contentify/contents/new.html.erb
<%- content_for :head do-%>
<title>管理画面 | 記事 | 新規作成</title>
<%- end -%>
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <div class="card">
      <%= form_for(@content, url: contents_path, method: :post) do |f| %>
      <div class="card-content">
        <span class="card-title black-text">記事&nbsp;新規作成</span>
        <%= render 'registration', f: f %>
      </div>
      <div class="card-action center-align">
        <%= f.button '作成する', class: 'waves-effect waves-light btn white-text wine-red', data: { confirm: '作成してもよろしいですか?' } %>
      </div>
      <% end %>
    </div>
  </div>
</div>